@startuml

class Spiel{
    -spielerListe: Spieler[]
    -ladenListe: Laden[]
    -lieferkartenStapel: Lieferkarte[]
    -muelleimer: Lieferkarte[]

    +spielverlauf(): void
    -anstellenInDenWarteschlangen(): void
    -warenlieferung(): void
    -draengelei(): void
    -ladenoeffnung(): void
    -tauschenAufDemMarkt(): void
    -aufraeumphase(): void

    -samstag(): void
}

@enduml